### ISSUE TITLE
Kontakty nie sortują się według dostępności

### ISSUE THREAD

**Issue by emkarcinos** [Wirus006/Software-enginieering#28]

**Comment by emkarcinos** [comment]
Właśnie, jeszcze poza sortowaniem wg dostępności, powinien być jakiś porządek i kontakty powinny się sortować alfabetycznie. Dostępność -> alfabet.

**Comment by itchystone** [comment]
Nie dodano sortowania alfabetycznie w obrębie grupy dostępności, otwieram ponownie
