### ISSUE TITLE
Brak podpisu ze stanem dostępności pod nazwą kontaktu

### ISSUE THREAD

**Issue by emkarcinos** [Wirus006/Software-enginieering#29]
Ustaliliśmy ostatnio, że oprócz nazwy kontaktu powinien być jakiś komunikat małą czcionką o stanie dostępności, bo żeby się dowiedzieć, czy jakiś kontakt jest dostępny w tym momencie, to muszę przeklikać, aż znajdę.

**Comment by itchystone** [comment]
Stwierdzono, że jednak feature zostanie pominięty.
